#!/bin/sh
set -eu

asc=
hashf=
hasha=
while [ $# -gt 0 ]; do
    case "$1" in
        -a) asc="x" ;;
        -s) hashf="sha1" ;;
        -m) hashf="md5" ;;
        -as) hasha="sha1" ;;
        -am) hasha="md5" ;;
        -*) echo "invalid option: $1" >&2 ; exit 1 ;;
        *) break ;;
    esac
    shift
done

url=$1
file=${url##*/}

set --
set -- -O "$url"
if [ "$asc" ]; then
    set -- "$@" -O "$url.asc"
    if [ "$hasha" ]; then
        set -- "$@" -O "$url.asc.$hasha"
    fi
fi
if [ "$hashf" ]; then
    set -- "$@" -O "$url.$hashf"
fi

if ! curl -LSs --fail --fail-early "$@"; then
    echo "Failed to download one of the files:" >&2
    for u in "$@"; do
        [ "$u" != "-O" ] && echo "  - $u" >&2
    done
    exit 1
fi

verify_hash() {
    sum=$(head -n1 $1.$2 | cut -d ' ' -f 1)
    echo "$sum $1" | ${2}sum -c -
    rm $1.$2
}

if [ "$hashf" ]; then
    verify_hash $file $hashf
fi
if [ "$asc" -a "$hasha" ]; then
    verify_hash $file.asc $hasha
fi
if [ "$asc" ]; then
    gpg2 --verify $file.asc 2>&1
    rm $file.asc
fi
